function sys = mylinearizeblock(op)
% MYLINEARIZEBLOCK Linearize the Simulink block - Atomic Subsystem.
%
% SYS = MYLINEARIZEBLOCK(OP) linearizes the Simulink block Atomic Subsystem about
% the operating point OP.

% M-File generated by MATLAB(R) 7.12 and Simulink Control Design (TM) 3.3.
%
% Generated on: 02-Apr-2016 23:08:20

%% Specify the model name
model = 'atomic_bitches';

%% Linearize the block
sys = linearize(model,op,'atomic_bitches/Atomic Subsystem');

%% Plot the resulting linearization.
step(sys)
